python train.py \
    --model_name_or_path /data/yh/bigscience_bloom-1b1 \
    --data_path /data/yh/WuDaoCorpus2.0_base_200G \
    --data_num_limit 60 \
    --data_proc_num 40 \
    --bf16 False \
    --output_dir output_dir \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --logging_steps 10 \
    --tf32 False \
    --model_max_length 1024 \
    --use_streaming True\
    --max_steps 10000